/*
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 *
 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
*/

create index IDX_ACADEMIC_CLASSIFICATION_SESSION on ACADEMIC_CLASSIFICATION(SESSION_ID);
create index IDX_ADVISOR_ROLE on ADVISOR(ROLE_ID);
create index IDX_ADVISOR_SESSION on ADVISOR(SESSION_ID);
create index IDX_ADVISOR_CRSREQ_COURSE_OFFERING on ADVISOR_CRSREQ(COURSE_OFFERING_ID);
create index IDX_ADVISOR_CRSREQ_FREE_TIME on ADVISOR_CRSREQ(FREE_TIME_ID);
create index IDX_ADVISOR_SECT_PREF_CLASS on ADVISOR_SECT_PREF(CLASS_ID);
create index IDX_ADVISOR_SECT_PREF_INSTR_MTHD on ADVISOR_SECT_PREF(INSTR_MTHD_ID);
create index IDX_ADVISOR_SECT_PREF_REQUEST on ADVISOR_SECT_PREF(REQUEST_ID);
create index IDX_ASSIGNED_INSTRUCTORS_INSTRUCTOR on ASSIGNED_INSTRUCTORS(INSTRUCTOR_ID);
create index IDX_ASSIGNMENT_DATE_PATTERN on ASSIGNMENT(DATE_PATTERN_ID);
create index IDX_ATTRIBUTE_DEPARTMENT on ATTRIBUTE(DEPARTMENT_ID);
create index IDX_ATTRIBUTE_PARENT on ATTRIBUTE(PARENT_ID);
create index IDX_ATTRIBUTE_SESSION on ATTRIBUTE(SESSION_ID);
create index IDX_ATTRIBUTE_TYPE on ATTRIBUTE(TYPE_ID);
create index IDX_ATTRIBUTE_PREF_ATTRIBUTE on ATTRIBUTE_PREF(ATTRIBUTE_ID);
create index IDX_ATTRIBUTE_PREF_PREF_LEVEL on ATTRIBUTE_PREF(PREF_LEVEL_ID);
create index IDX_CHANGE_LOG_MANAGER on CHANGE_LOG(MANAGER_ID);
create index IDX_CLASS__FUNDING_DEPT on CLASS_(FUNDING_DEPT_ID);
create index IDX_CLASS__LMS_INFO on CLASS_(LMS_INFO_ID);
create index IDX_CLASS_INSTRUCTOR_REQUEST on CLASS_INSTRUCTOR(REQUEST_ID);
create index IDX_CLASS_INSTRUCTOR_RESPONSIBILITY on CLASS_INSTRUCTOR(RESPONSIBILITY_ID);
create index IDX_COURSE_CREDIT_UNIT_CONFIG_COURSE on COURSE_CREDIT_UNIT_CONFIG(COURSE_ID);
create index IDX_COURSE_OFFERING_CONSENT_TYPE on COURSE_OFFERING(CONSENT_TYPE);
create index IDX_COURSE_OFFERING_COURSE_TYPE on COURSE_OFFERING(COURSE_TYPE_ID);
create index IDX_COURSE_OFFERING_FUNDING_DEPT on COURSE_OFFERING(FUNDING_DEPT_ID);
create index IDX_COURSE_PREF_COURSE on COURSE_PREF(COURSE_ID);
create index IDX_COURSE_PREF_PREF_LEVEL on COURSE_PREF(PREF_LEVEL_ID);
create index IDX_COURSE_SUBPART_CREDIT_COURSE_CATALOG on COURSE_SUBPART_CREDIT(COURSE_CATALOG_ID);
create index IDX_CURRICULUM_ACAD_AREA on CURRICULUM(ACAD_AREA_ID);
create index IDX_CURRICULUM_DEPT on CURRICULUM(DEPT_ID);
create index IDX_CURRICULUM_CLASF_ACAD_CLASF on CURRICULUM_CLASF(ACAD_CLASF_ID);
create index IDX_CURRICULUM_CLASF_CURRICULUM on CURRICULUM_CLASF(CURRICULUM_ID);
create index IDX_CURRICULUM_COURSE_CUR_CLASF on CURRICULUM_COURSE(CUR_CLASF_ID);
create index IDX_CURRICULUM_COURSE_COURSE on CURRICULUM_COURSE(COURSE_ID);
create index IDX_CURRICULUM_COURSE_GROUP_CUR_COURSE on CURRICULUM_COURSE_GROUP(CUR_COURSE_ID);
create index IDX_CURRICULUM_GROUP_CURRICULUM on CURRICULUM_GROUP(CURRICULUM_ID);
create index IDX_CURRICULUM_MAJOR_MAJOR on CURRICULUM_MAJOR(MAJOR_ID);
create index IDX_CURRICULUM_RULE_ACAD_CLASF on CURRICULUM_RULE(ACAD_CLASF_ID);
create index IDX_CURRICULUM_RULE_MAJOR on CURRICULUM_RULE(MAJOR_ID);
create index IDX_DATE_MAPPING_SESSION on DATE_MAPPING(SESSION_ID);
create index IDX_DATE_PATTERN_DEPT_PATTERN on DATE_PATTERN_DEPT(PATTERN_ID);
create index IDX_DATE_PATTERN_PARENT_PARENT on DATE_PATTERN_PARENT(PARENT_ID);
create index IDX_DATE_PATTERN_PREF_DATE_PATTERN on DATE_PATTERN_PREF(DATE_PATTERN_ID);
create index IDX_DATE_PATTERN_PREF_PREF_LEVEL on DATE_PATTERN_PREF(PREF_LEVEL_ID);
create index IDX_DEPARTMENTAL_INSTRUCTOR_TEACHING_PREF on DEPARTMENTAL_INSTRUCTOR(TEACHING_PREF_ID);
create index IDX_DEPARTMENTAL_INSTRUCTOR_ROLE on DEPARTMENTAL_INSTRUCTOR(ROLE_ID);
create index IDX_DEPT_TO_TT_MGR_DEPARTMENT on DEPT_TO_TT_MGR(DEPARTMENT_ID);
create index IDX_DESIGNATOR_INSTRUCTOR on DESIGNATOR(INSTRUCTOR_ID);
create index IDX_DISABLED_OVERRIDE_TYPE on DISABLED_OVERRIDE(TYPE_ID);
create index IDX_DIST_TYPE_DEPT_DEPT on DIST_TYPE_DEPT(DEPT_ID);
create index IDX_EVENT_SPONSOR_ORG on EVENT(SPONSOR_ORG_ID);
create index IDX_EVENT_JOIN_EVENT_CONTACT_EVENT_CONTACT on EVENT_JOIN_EVENT_CONTACT(EVENT_CONTACT_ID);
create index IDX_EVENT_NOTE_MEETING_MEETING on EVENT_NOTE_MEETING(MEETING_ID);
create index IDX_EVENT_SERVICE_PROVIDER_PROVIDER on EVENT_SERVICE_PROVIDER(PROVIDER_ID);
create index IDX_EXAM_ASSIGNED_PERIOD on EXAM(ASSIGNED_PERIOD);
create index IDX_EXAM_SESSION on EXAM(SESSION_ID);
create index IDX_EXAM_EXAM_TYPE on EXAM(EXAM_TYPE_ID);
create index IDX_EXAM_INSTRUCTOR_INSTRUCTOR on EXAM_INSTRUCTOR(INSTRUCTOR_ID);
create index IDX_EXAM_LOCATION_PREF_PERIOD on EXAM_LOCATION_PREF(PERIOD_ID);
create index IDX_EXAM_LOCATION_PREF_PREF_LEVEL on EXAM_LOCATION_PREF(PREF_LEVEL_ID);
create index IDX_EXAM_MANAGERS_MANAGER on EXAM_MANAGERS(MANAGER_ID);
create index IDX_EXAM_PERIOD_PREF_LEVEL on EXAM_PERIOD(PREF_LEVEL_ID);
create index IDX_EXAM_PERIOD_SESSION on EXAM_PERIOD(SESSION_ID);
create index IDX_EXAM_PERIOD_EXAM_TYPE on EXAM_PERIOD(EXAM_TYPE_ID);
create index IDX_EXAM_PERIOD_PREF_PERIOD on EXAM_PERIOD_PREF(PERIOD_ID);
create index IDX_EXAM_PERIOD_PREF_PREF_LEVEL on EXAM_PERIOD_PREF(PREF_LEVEL_ID);
create index IDX_EXAM_STATUS_STATUS on EXAM_STATUS(STATUS_ID);
create index IDX_EXAM_STATUS_TYPE on EXAM_STATUS(TYPE_ID);
create index IDX_EXTERNAL_ROOM_ROOM_TYPE on EXTERNAL_ROOM(ROOM_TYPE);
create index IDX_EXTERNAL_ROOM_DEPARTMENT_EXTERNAL_ROOM on EXTERNAL_ROOM_DEPARTMENT(EXTERNAL_ROOM_ID);
create index IDX_EXTERNAL_ROOM_FEATURE_EXTERNAL_ROOM on EXTERNAL_ROOM_FEATURE(EXTERNAL_ROOM_ID);
create index IDX_EXT_DEPT_STATUS_DEPARTMENT on EXT_DEPT_STATUS(DEPARTMENT_ID);
create index IDX_EXT_DEPT_STATUS_STATUS_TYPE on EXT_DEPT_STATUS(STATUS_TYPE);
create index IDX_FREE_TIME_SESSION on FREE_TIME(SESSION_ID);
create index IDX_INSTRUCTOR_ATTRIBUTES_INSTRUCTOR on INSTRUCTOR_ATTRIBUTES(INSTRUCTOR_ID);
create index IDX_INSTRUCTOR_PREF_INSTRUCTOR on INSTRUCTOR_PREF(INSTRUCTOR_ID);
create index IDX_INSTRUCTOR_PREF_PREF_LEVEL on INSTRUCTOR_PREF(PREF_LEVEL_ID);
create index IDX_INSTRUCTOR_SURVEY_SESSION on INSTRUCTOR_SURVEY(SESSION_ID);
create index IDX_INSTR_CRSREQ_COURSE_OFFERING on INSTR_CRSREQ(COURSE_OFFERING_ID);
create index IDX_INSTR_CRSREQ_SURVEY on INSTR_CRSREQ(SURVEY_ID);
create index IDX_INSTR_CRSREQ_NOTE_TYPE on INSTR_CRSREQ_NOTE(TYPE_ID);
create index IDX_INSTR_OFFERING_CONFIG_DURATION_TYPE on INSTR_OFFERING_CONFIG(DURATION_TYPE_ID);
create index IDX_INSTR_OFFERING_CONFIG_INSTR_METHOD on INSTR_OFFERING_CONFIG(INSTR_METHOD_ID);
create index IDX_ITYPE_DESC_PARENT on ITYPE_DESC(PARENT);
create index IDX_LOCATION_PICTURE_LOCATION on LOCATION_PICTURE(LOCATION_ID);
create index IDX_LOCATION_PICTURE_TYPE on LOCATION_PICTURE(TYPE_ID);
create index IDX_LOCATION_SERVICE_PROVIDER_PROVIDER on LOCATION_SERVICE_PROVIDER(PROVIDER_ID);
create index IDX_MEETING_CONTACT_CONTACT on MEETING_CONTACT(CONTACT_ID);
create index IDX_NON_UNIVERSITY_LOCATION_ROOM_TYPE on NON_UNIVERSITY_LOCATION(ROOM_TYPE);
create index IDX_NON_UNIVERSITY_LOCATION_EVENT_DEPT on NON_UNIVERSITY_LOCATION(EVENT_DEPT_ID);
create index IDX_OFFERING_COORDINATOR_REQUEST on OFFERING_COORDINATOR(REQUEST_ID);
create index IDX_OFFERING_COORDINATOR_RESPONSIBILITY on OFFERING_COORDINATOR(RESPONSIBILITY_ID);
create index IDX_OFFERING_COORDINATOR_INSTRUCTOR on OFFERING_COORDINATOR(INSTRUCTOR_ID);
create index IDX_OFFERING_COORDINATOR_OFFERING on OFFERING_COORDINATOR(OFFERING_ID);
create index IDX_OFFR_GROUP_OFFERING_INSTR_OFFERING on OFFR_GROUP_OFFERING(INSTR_OFFERING_ID);
create index IDX_PIT_CLASS_FUNDING_DEPT on PIT_CLASS(FUNDING_DEPT_ID);
create index IDX_PIT_CLASS_CLASS on PIT_CLASS(CLASS_ID);
create index IDX_PIT_CLASS_MANAGING_DEPT on PIT_CLASS(MANAGING_DEPT);
create index IDX_PIT_CLASS_DATE_PATTERN on PIT_CLASS(DATE_PATTERN_ID);
create index IDX_PIT_CLASS_PIT_PARENT on PIT_CLASS(PIT_PARENT_ID);
create index IDX_PIT_CLASS_PIT_SUBPART on PIT_CLASS(PIT_SUBPART_ID);
create index IDX_PIT_CLASS_TIME_PATTERN on PIT_CLASS(TIME_PATTERN_ID);
create index IDX_PIT_CLASS_EVENT_PIT_CLASS on PIT_CLASS_EVENT(PIT_CLASS_ID);
create index IDX_PIT_CLASS_INSTRUCTOR_PIT_CLASS on PIT_CLASS_INSTRUCTOR(PIT_CLASS_ID);
create index IDX_PIT_CLASS_INSTRUCTOR_PIT_DEPT_INSTR on PIT_CLASS_INSTRUCTOR(PIT_DEPT_INSTR_ID);
create index IDX_PIT_CLASS_INSTRUCTOR_RESPONSIBILITY on PIT_CLASS_INSTRUCTOR(RESPONSIBILITY_ID);
create index IDX_PIT_CLASS_MEETING_PIT_CLASS_EVENT on PIT_CLASS_MEETING(PIT_CLASS_EVENT_ID);
create index IDX_PIT_CLASS_MTG_UTIL_PERIOD_PIT_CLASS_MEETING on PIT_CLASS_MTG_UTIL_PERIOD(PIT_CLASS_MEETING_ID);
create index IDX_PIT_COURSE_OFFERING_COURSE_OFFERING on PIT_COURSE_OFFERING(COURSE_OFFERING_ID);
create index IDX_PIT_COURSE_OFFERING_COURSE_TYPE on PIT_COURSE_OFFERING(COURSE_TYPE_ID);
create index IDX_PIT_COURSE_OFFERING_PIT_INSTR_OFFR on PIT_COURSE_OFFERING(PIT_INSTR_OFFR_ID);
create index IDX_PIT_COURSE_OFFERING_SUBJECT_AREA on PIT_COURSE_OFFERING(SUBJECT_AREA_ID);
create index IDX_PIT_DEPT_INSTRUCTOR_DEPARTMENT on PIT_DEPT_INSTRUCTOR(DEPARTMENT_ID);
create index IDX_PIT_DEPT_INSTRUCTOR_DEPT_INSTRUCTOR on PIT_DEPT_INSTRUCTOR(DEPT_INSTRUCTOR_ID);
create index IDX_PIT_DEPT_INSTRUCTOR_POINT_IN_TIME_DATA on PIT_DEPT_INSTRUCTOR(POINT_IN_TIME_DATA_ID);
create index IDX_PIT_DEPT_INSTRUCTOR_POS_CODE_TYPE on PIT_DEPT_INSTRUCTOR(POS_CODE_TYPE);
create index IDX_PIT_INSTR_OFFERING_INSTR_OFFERING on PIT_INSTR_OFFERING(INSTR_OFFERING_ID);
create index IDX_PIT_INSTR_OFFERING_POINT_IN_TIME_DATA on PIT_INSTR_OFFERING(POINT_IN_TIME_DATA_ID);
create index IDX_PIT_INSTR_OFFER_CONFIG_DURATION_TYPE on PIT_INSTR_OFFER_CONFIG(DURATION_TYPE_ID);
create index IDX_PIT_INSTR_OFFER_CONFIG_INSTR_METHOD on PIT_INSTR_OFFER_CONFIG(INSTR_METHOD_ID);
create index IDX_PIT_INSTR_OFFER_CONFIG_INSTR_OFFERING_CONFIG on PIT_INSTR_OFFER_CONFIG(INSTR_OFFERING_CONFIG_ID);
create index IDX_PIT_INSTR_OFFER_CONFIG_PIT_INSTR_OFFR on PIT_INSTR_OFFER_CONFIG(PIT_INSTR_OFFR_ID);
create index IDX_PIT_OFFERING_COORD_RESPONSIBILITY on PIT_OFFERING_COORD(RESPONSIBILITY_ID);
create index IDX_PIT_OFFERING_COORD_PIT_DEPT_INSTR on PIT_OFFERING_COORD(PIT_DEPT_INSTR_ID);
create index IDX_PIT_OFFERING_COORD_PIT_OFFERING on PIT_OFFERING_COORD(PIT_OFFERING_ID);
create index IDX_PIT_SCHED_SUBPART_ITYPE on PIT_SCHED_SUBPART(ITYPE);
create index IDX_PIT_SCHED_SUBPART_PIT_PARENT on PIT_SCHED_SUBPART(PIT_PARENT_ID);
create index IDX_PIT_SCHED_SUBPART_PIT_CONFIG on PIT_SCHED_SUBPART(PIT_CONFIG_ID);
create index IDX_PIT_SCHED_SUBPART_SCHEDULING_SUBPART on PIT_SCHED_SUBPART(SCHEDULING_SUBPART_ID);
create index IDX_PIT_STUDENT_POINT_IN_TIME_DATA on PIT_STUDENT(POINT_IN_TIME_DATA_ID);
create index IDX_PIT_STUDENT_STUDENT on PIT_STUDENT(STUDENT_ID);
create index IDX_PIT_STUDENT_CLASS_ENRL_PIT_CLASS on PIT_STUDENT_CLASS_ENRL(PIT_CLASS_ID);
create index IDX_PIT_STUDENT_CLASS_ENRL_PIT_COURSE_OFFERING on PIT_STUDENT_CLASS_ENRL(PIT_COURSE_OFFERING_ID);
create index IDX_PIT_STUDENT_CLASS_ENRL_PIT_STUDENT on PIT_STUDENT_CLASS_ENRL(PIT_STUDENT_ID);
create index IDX_PIT_STU_AA_MAJOR_CLASF_ACAD_AREA on PIT_STU_AA_MAJOR_CLASF(ACAD_AREA_ID);
create index IDX_PIT_STU_AA_MAJOR_CLASF_ACAD_CLASF on PIT_STU_AA_MAJOR_CLASF(ACAD_CLASF_ID);
create index IDX_PIT_STU_AA_MAJOR_CLASF_CONCENTRATION on PIT_STU_AA_MAJOR_CLASF(CONCENTRATION_ID);
create index IDX_PIT_STU_AA_MAJOR_CLASF_PIT_STUDENT on PIT_STU_AA_MAJOR_CLASF(PIT_STUDENT_ID);
create index IDX_PIT_STU_AA_MAJOR_CLASF_MAJOR on PIT_STU_AA_MAJOR_CLASF(MAJOR_ID);
create index IDX_PIT_STU_AA_MINOR_CLASF_ACAD_AREA on PIT_STU_AA_MINOR_CLASF(ACAD_AREA_ID);
create index IDX_PIT_STU_AA_MINOR_CLASF_ACAD_CLASF on PIT_STU_AA_MINOR_CLASF(ACAD_CLASF_ID);
create index IDX_PIT_STU_AA_MINOR_CLASF_PIT_STUDENT on PIT_STU_AA_MINOR_CLASF(PIT_STUDENT_ID);
create index IDX_PIT_STU_AA_MINOR_CLASF_MINOR on PIT_STU_AA_MINOR_CLASF(MINOR_ID);
create index IDX_POINT_IN_TIME_DATA_SESSION on POINT_IN_TIME_DATA(SESSION_ID);
create index IDX_POS_ACAD_AREA_MAJOR_MAJOR on POS_ACAD_AREA_MAJOR(MAJOR_ID);
create index IDX_POS_ACAD_AREA_MINOR_MINOR on POS_ACAD_AREA_MINOR(MINOR_ID);
create index IDX_POS_MAJOR_SESSION on POS_MAJOR(SESSION_ID);
create index IDX_POS_MAJOR_CONC_MAJOR on POS_MAJOR_CONC(MAJOR_ID);
create index IDX_POS_MINOR_SESSION on POS_MINOR(SESSION_ID);
create index IDX_RELATED_COURSE_INFO_COURSE on RELATED_COURSE_INFO(COURSE_ID);
create index IDX_RESERVATION_COURSE on RESERVATION(COURSE_ID);
create index IDX_RESERVATION_OFFERING on RESERVATION(OFFERING_ID);
create index IDX_RESERVATION_GROUP on RESERVATION(GROUP_ID);
create index IDX_RESERVATION_ACAD_AREA_AREA on RESERVATION_ACAD_AREA(AREA_ID);
create index IDX_RESERVATION_CLASF_ACAD_CLASF on RESERVATION_CLASF(ACAD_CLASF_ID);
create index IDX_RESERVATION_CLASS_CLASS on RESERVATION_CLASS(CLASS_ID);
create index IDX_RESERVATION_CONFIG_CONFIG on RESERVATION_CONFIG(CONFIG_ID);
create index IDX_RESERVATION_MAJOR_MAJOR on RESERVATION_MAJOR(MAJOR_ID);
create index IDX_RESERVATION_MAJOR_CONC_CONCENTRATION on RESERVATION_MAJOR_CONC(CONCENTRATION_ID);
create index IDX_RESERVATION_MINOR_MINOR on RESERVATION_MINOR(MINOR_ID);
create index IDX_RESERVATION_STUDENT_STUDENT on RESERVATION_STUDENT(STUDENT_ID);
create index IDX_ROOM_EVENT_DEPT on ROOM(EVENT_DEPT_ID);
create index IDX_ROOM_PARENT_ROOM on ROOM(PARENT_ROOM_ID);
create index IDX_ROOM_ROOM_TYPE on ROOM(ROOM_TYPE);
create index IDX_ROOM_EXAM_TYPE_EXAM_TYPE on ROOM_EXAM_TYPE(EXAM_TYPE_ID);
create index IDX_ROOM_FEATURE_FEATURE_TYPE on ROOM_FEATURE(FEATURE_TYPE_ID);
create index IDX_ROOM_FEATURE_SESSION on ROOM_FEATURE(SESSION_ID);
create index IDX_ROOM_JOIN_ROOM_FEATURE_FEATURE on ROOM_JOIN_ROOM_FEATURE(FEATURE_ID);
create index IDX_ROOM_PICTURE_LOCATION on ROOM_PICTURE(LOCATION_ID);
create index IDX_ROOM_PICTURE_TYPE on ROOM_PICTURE(TYPE_ID);
create index IDX_ROOM_SERVICE_PROVIDER_PROVIDER on ROOM_SERVICE_PROVIDER(PROVIDER_ID);
create index IDX_ROOM_TYPE_OPTION_DEPARTMENT on ROOM_TYPE_OPTION(DEPARTMENT_ID);
create index IDX_SCT_SOLUTION_LOG_OWNER on SCT_SOLUTION_LOG(OWNER_ID);
create index IDX_SCT_SOLUTION_LOG_SESSION on SCT_SOLUTION_LOG(SESSION_ID);
create index IDX_SECTIONING_COURSE_TYPES_COURSE_TYPE on SECTIONING_COURSE_TYPES(COURSE_TYPE_ID);
create index IDX_SECTIONING_INFO_CLASS on SECTIONING_INFO(CLASS_ID);
create index IDX_SECTIONING_LOG_SESSION on SECTIONING_LOG(SESSION_ID);
create index IDX_SECTIONING_STATUS_FALLBACK on SECTIONING_STATUS(FALLBACK_ID);
create index IDX_SECTIONING_STATUS_SESSION on SECTIONING_STATUS(SESSION_ID);
create index IDX_SERVICE_PROVIDER_DEPARTMENT on SERVICE_PROVIDER(DEPARTMENT_ID);
create index IDX_SERVICE_PROVIDER_SESSION on SERVICE_PROVIDER(SESSION_ID);
create index IDX_SESSIONS_DURATION_TYPE on SESSIONS(DURATION_TYPE_ID);
create index IDX_SESSIONS_INSTR_METHOD on SESSIONS(INSTR_METHOD_ID);
create index IDX_SESSIONS_SECT_STATUS on SESSIONS(SECT_STATUS);
create index IDX_SOLVER_GR_TO_TT_MGR_TIMETABLE_MGR on SOLVER_GR_TO_TT_MGR(TIMETABLE_MGR_ID);
create index IDX_SOLVER_INFO_SOLVER_INFO_DEF on SOLVER_INFO(SOLVER_INFO_DEF_ID);
create index IDX_STAFF_POS_TYPE on STAFF(POS_TYPE);
create index IDX_STANDARD_EVENT_NOTE_DEPARTMENT on STANDARD_EVENT_NOTE(DEPARTMENT_ID);
create index IDX_STANDARD_EVENT_NOTE_SESSION on STANDARD_EVENT_NOTE(SESSION_ID);
create index IDX_STUDENT_SECT_STATUS on STUDENT(SECT_STATUS);
create index IDX_STUDENT_ACAD_AREA_ACAD_AREA on STUDENT_ACAD_AREA(ACAD_AREA_ID);
create index IDX_STUDENT_ACAD_AREA_ACAD_CLASF on STUDENT_ACAD_AREA(ACAD_CLASF_ID);
create index IDX_STUDENT_ACCOMODATION_SESSION on STUDENT_ACCOMODATION(SESSION_ID);
create index IDX_STUDENT_ADVISOR_ADVISOR on STUDENT_ADVISOR(ADVISOR_ID);
create index IDX_STUDENT_AREA_CLASF_MAJOR_ACAD_AREA on STUDENT_AREA_CLASF_MAJOR(ACAD_AREA_ID);
create index IDX_STUDENT_AREA_CLASF_MAJOR_CAMPUS on STUDENT_AREA_CLASF_MAJOR(CAMPUS_ID);
create index IDX_STUDENT_AREA_CLASF_MAJOR_ACAD_CLASF on STUDENT_AREA_CLASF_MAJOR(ACAD_CLASF_ID);
create index IDX_STUDENT_AREA_CLASF_MAJOR_CONCENTRATION on STUDENT_AREA_CLASF_MAJOR(CONCENTRATION_ID);
create index IDX_STUDENT_AREA_CLASF_MAJOR_DEGREE on STUDENT_AREA_CLASF_MAJOR(DEGREE_ID);
create index IDX_STUDENT_AREA_CLASF_MAJOR_MAJOR on STUDENT_AREA_CLASF_MAJOR(MAJOR_ID);
create index IDX_STUDENT_AREA_CLASF_MAJOR_PROGRAM on STUDENT_AREA_CLASF_MAJOR(PROGRAM_ID);
create index IDX_STUDENT_AREA_CLASF_MINOR_ACAD_AREA on STUDENT_AREA_CLASF_MINOR(ACAD_AREA_ID);
create index IDX_STUDENT_AREA_CLASF_MINOR_ACAD_CLASF on STUDENT_AREA_CLASF_MINOR(ACAD_CLASF_ID);
create index IDX_STUDENT_AREA_CLASF_MINOR_MINOR on STUDENT_AREA_CLASF_MINOR(MINOR_ID);
create index IDX_STUDENT_GROUP_TYPE on STUDENT_GROUP(TYPE_ID);
create index IDX_STUDENT_MAJOR_MAJOR on STUDENT_MAJOR(MAJOR_ID);
create index IDX_STUDENT_MINOR_MINOR on STUDENT_MINOR(MINOR_ID);
create index IDX_STUDENT_TO_ACOMODATION_ACCOMODATION on STUDENT_TO_ACOMODATION(ACCOMODATION_ID);
create index IDX_STUDENT_TO_GROUP_GROUP on STUDENT_TO_GROUP(GROUP_ID);
create index IDX_SUBJECT_AREA_FUNDING_DEPT on SUBJECT_AREA(FUNDING_DEPT_ID);
create index IDX_TASK_OWNER on TASK(OWNER_ID);
create index IDX_TASK_SCRIPT on TASK(SCRIPT_ID);
create index IDX_TASK_SESSION on TASK(SESSION_ID);
create index IDX_TASK_EXECUTION_TASK on TASK_EXECUTION(TASK_ID);
create index IDX_TEACHING_REQUEST_OFFERING on TEACHING_REQUEST(OFFERING_ID);
create index IDX_TEACHING_REQUEST_RESPONSIBILITY on TEACHING_REQUEST(RESPONSIBILITY_ID);
create index IDX_TEACHING_REQUEST_SAME_COMMON_PREF on TEACHING_REQUEST(SAME_COMMON_PREF);
create index IDX_TEACHING_REQUEST_SAME_COURSE_PREF on TEACHING_REQUEST(SAME_COURSE_PREF);
create index IDX_TEACHREQ_CLASS_CLASS on TEACHREQ_CLASS(CLASS_ID);
create index IDX_TEACHREQ_CLASS_REQUEST on TEACHREQ_CLASS(REQUEST_ID);
create index IDX_TEACHREQ_INSTRUCTOR_INSTRUCTOR on TEACHREQ_INSTRUCTOR(INSTRUCTOR_ID);
create index IDX_TIME_PATTERN_DEPT_PATTERN on TIME_PATTERN_DEPT(PATTERN_ID);
create index IDX_TMTBL_MGR_TO_ROLES_ROLE on TMTBL_MGR_TO_ROLES(ROLE_ID);
create index IDX_TRAVEL_TIME_SESSION on TRAVEL_TIME(SESSION_ID);
create index IDX_XCONFLICT_INSTRUCTOR_INSTRUCTOR on XCONFLICT_INSTRUCTOR(INSTRUCTOR_ID);
create index IDX_XCONFLICT_STUDENT_STUDENT on XCONFLICT_STUDENT(STUDENT_ID);

/*
 * Update database version
 */
  
update application_config set value='270' where name='tmtbl.db.version';

commit;
