/*
 * Licensed to The Apereo Foundation under one or more contributor license
 * agreements. See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 *
 * The Apereo Foundation licenses this file to you under the Apache License,
 * Version 2.0  USING btree (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
*/

create index IDX_ACADEMIC_CLASSIFICATION_SESSION on ACADEMIC_CLASSIFICATION USING btree (SESSION_ID);
create index IDX_ADVISOR_ROLE on ADVISOR USING btree (ROLE_ID);
create index IDX_ADVISOR_SESSION on ADVISOR USING btree (SESSION_ID);
create index IDX_ADVISOR_CRSREQ_COURSE_OFFERING on ADVISOR_CRSREQ USING btree (COURSE_OFFERING_ID);
create index IDX_ADVISOR_CRSREQ_FREE_TIME on ADVISOR_CRSREQ USING btree (FREE_TIME_ID);
create index IDX_ADVISOR_SECT_PREF_CLASS on ADVISOR_SECT_PREF USING btree (CLASS_ID);
create index IDX_ADVISOR_SECT_PREF_INSTR_MTHD on ADVISOR_SECT_PREF USING btree (INSTR_MTHD_ID);
create index IDX_ADVISOR_SECT_PREF_REQUEST on ADVISOR_SECT_PREF USING btree (REQUEST_ID);
create index IDX_ASSIGNED_INSTRUCTORS_INSTRUCTOR on ASSIGNED_INSTRUCTORS USING btree (INSTRUCTOR_ID);
create index IDX_ASSIGNMENT_DATE_PATTERN on ASSIGNMENT USING btree (DATE_PATTERN_ID);
create index IDX_ATTRIBUTE_DEPARTMENT on ATTRIBUTE USING btree (DEPARTMENT_ID);
create index IDX_ATTRIBUTE_PARENT on ATTRIBUTE USING btree (PARENT_ID);
create index IDX_ATTRIBUTE_SESSION on ATTRIBUTE USING btree (SESSION_ID);
create index IDX_ATTRIBUTE_TYPE on ATTRIBUTE USING btree (TYPE_ID);
create index IDX_ATTRIBUTE_PREF_ATTRIBUTE on ATTRIBUTE_PREF USING btree (ATTRIBUTE_ID);
create index IDX_ATTRIBUTE_PREF_PREF_LEVEL on ATTRIBUTE_PREF USING btree (PREF_LEVEL_ID);
create index IDX_CHANGE_LOG_MANAGER on CHANGE_LOG USING btree (MANAGER_ID);
create index IDX_CLASS__FUNDING_DEPT on CLASS_ USING btree (FUNDING_DEPT_ID);
create index IDX_CLASS__LMS_INFO on CLASS_ USING btree (LMS_INFO_ID);
create index IDX_CLASS_INSTRUCTOR_REQUEST on CLASS_INSTRUCTOR USING btree (REQUEST_ID);
create index IDX_CLASS_INSTRUCTOR_RESPONSIBILITY on CLASS_INSTRUCTOR USING btree (RESPONSIBILITY_ID);
create index IDX_COURSE_CREDIT_UNIT_CONFIG_COURSE on COURSE_CREDIT_UNIT_CONFIG USING btree (COURSE_ID);
create index IDX_COURSE_OFFERING_CONSENT_TYPE on COURSE_OFFERING USING btree (CONSENT_TYPE);
create index IDX_COURSE_OFFERING_COURSE_TYPE on COURSE_OFFERING USING btree (COURSE_TYPE_ID);
create index IDX_COURSE_OFFERING_FUNDING_DEPT on COURSE_OFFERING USING btree (FUNDING_DEPT_ID);
create index IDX_COURSE_PREF_COURSE on COURSE_PREF USING btree (COURSE_ID);
create index IDX_COURSE_PREF_PREF_LEVEL on COURSE_PREF USING btree (PREF_LEVEL_ID);
create index IDX_COURSE_SUBPART_CREDIT_COURSE_CATALOG on COURSE_SUBPART_CREDIT USING btree (COURSE_CATALOG_ID);
create index IDX_CURRICULUM_ACAD_AREA on CURRICULUM USING btree (ACAD_AREA_ID);
create index IDX_CURRICULUM_DEPT on CURRICULUM USING btree (DEPT_ID);
create index IDX_CURRICULUM_CLASF_ACAD_CLASF on CURRICULUM_CLASF USING btree (ACAD_CLASF_ID);
create index IDX_CURRICULUM_CLASF_CURRICULUM on CURRICULUM_CLASF USING btree (CURRICULUM_ID);
create index IDX_CURRICULUM_COURSE_CUR_CLASF on CURRICULUM_COURSE USING btree (CUR_CLASF_ID);
create index IDX_CURRICULUM_COURSE_COURSE on CURRICULUM_COURSE USING btree (COURSE_ID);
create index IDX_CURRICULUM_COURSE_GROUP_CUR_COURSE on CURRICULUM_COURSE_GROUP USING btree (CUR_COURSE_ID);
create index IDX_CURRICULUM_GROUP_CURRICULUM on CURRICULUM_GROUP USING btree (CURRICULUM_ID);
create index IDX_CURRICULUM_MAJOR_MAJOR on CURRICULUM_MAJOR USING btree (MAJOR_ID);
create index IDX_CURRICULUM_RULE_ACAD_CLASF on CURRICULUM_RULE USING btree (ACAD_CLASF_ID);
create index IDX_CURRICULUM_RULE_MAJOR on CURRICULUM_RULE USING btree (MAJOR_ID);
create index IDX_DATE_MAPPING_SESSION on DATE_MAPPING USING btree (SESSION_ID);
create index IDX_DATE_PATTERN_DEPT_PATTERN on DATE_PATTERN_DEPT USING btree (PATTERN_ID);
create index IDX_DATE_PATTERN_PARENT_PARENT on DATE_PATTERN_PARENT USING btree (PARENT_ID);
create index IDX_DATE_PATTERN_PREF_DATE_PATTERN on DATE_PATTERN_PREF USING btree (DATE_PATTERN_ID);
create index IDX_DATE_PATTERN_PREF_PREF_LEVEL on DATE_PATTERN_PREF USING btree (PREF_LEVEL_ID);
create index IDX_DEPARTMENTAL_INSTRUCTOR_TEACHING_PREF on DEPARTMENTAL_INSTRUCTOR USING btree (TEACHING_PREF_ID);
create index IDX_DEPARTMENTAL_INSTRUCTOR_ROLE on DEPARTMENTAL_INSTRUCTOR USING btree (ROLE_ID);
create index IDX_DEPT_TO_TT_MGR_DEPARTMENT on DEPT_TO_TT_MGR USING btree (DEPARTMENT_ID);
create index IDX_DESIGNATOR_INSTRUCTOR on DESIGNATOR USING btree (INSTRUCTOR_ID);
create index IDX_DISABLED_OVERRIDE_TYPE on DISABLED_OVERRIDE USING btree (TYPE_ID);
create index IDX_DIST_TYPE_DEPT_DEPT on DIST_TYPE_DEPT USING btree (DEPT_ID);
create index IDX_EVENT_SPONSOR_ORG on EVENT USING btree (SPONSOR_ORG_ID);
create index IDX_EVENT_JOIN_EVENT_CONTACT_EVENT_CONTACT on EVENT_JOIN_EVENT_CONTACT USING btree (EVENT_CONTACT_ID);
create index IDX_EVENT_NOTE_MEETING_MEETING on EVENT_NOTE_MEETING USING btree (MEETING_ID);
create index IDX_EVENT_SERVICE_PROVIDER_PROVIDER on EVENT_SERVICE_PROVIDER USING btree (PROVIDER_ID);
create index IDX_EXAM_ASSIGNED_PERIOD on EXAM USING btree (ASSIGNED_PERIOD);
create index IDX_EXAM_SESSION on EXAM USING btree (SESSION_ID);
create index IDX_EXAM_EXAM_TYPE on EXAM USING btree (EXAM_TYPE_ID);
create index IDX_EXAM_INSTRUCTOR_INSTRUCTOR on EXAM_INSTRUCTOR USING btree (INSTRUCTOR_ID);
create index IDX_EXAM_LOCATION_PREF_PERIOD on EXAM_LOCATION_PREF USING btree (PERIOD_ID);
create index IDX_EXAM_LOCATION_PREF_PREF_LEVEL on EXAM_LOCATION_PREF USING btree (PREF_LEVEL_ID);
create index IDX_EXAM_MANAGERS_MANAGER on EXAM_MANAGERS USING btree (MANAGER_ID);
create index IDX_EXAM_PERIOD_PREF_LEVEL on EXAM_PERIOD USING btree (PREF_LEVEL_ID);
create index IDX_EXAM_PERIOD_SESSION on EXAM_PERIOD USING btree (SESSION_ID);
create index IDX_EXAM_PERIOD_EXAM_TYPE on EXAM_PERIOD USING btree (EXAM_TYPE_ID);
create index IDX_EXAM_PERIOD_PREF_PERIOD on EXAM_PERIOD_PREF USING btree (PERIOD_ID);
create index IDX_EXAM_PERIOD_PREF_PREF_LEVEL on EXAM_PERIOD_PREF USING btree (PREF_LEVEL_ID);
create index IDX_EXAM_STATUS_STATUS on EXAM_STATUS USING btree (STATUS_ID);
create index IDX_EXAM_STATUS_TYPE on EXAM_STATUS USING btree (TYPE_ID);
create index IDX_EXTERNAL_ROOM_ROOM_TYPE on EXTERNAL_ROOM USING btree (ROOM_TYPE);
create index IDX_EXTERNAL_ROOM_DEPARTMENT_EXTERNAL_ROOM on EXTERNAL_ROOM_DEPARTMENT USING btree (EXTERNAL_ROOM_ID);
create index IDX_EXTERNAL_ROOM_FEATURE_EXTERNAL_ROOM on EXTERNAL_ROOM_FEATURE USING btree (EXTERNAL_ROOM_ID);
create index IDX_EXT_DEPT_STATUS_DEPARTMENT on EXT_DEPT_STATUS USING btree (DEPARTMENT_ID);
create index IDX_EXT_DEPT_STATUS_STATUS_TYPE on EXT_DEPT_STATUS USING btree (STATUS_TYPE);
create index IDX_FREE_TIME_SESSION on FREE_TIME USING btree (SESSION_ID);
create index IDX_INSTRUCTOR_ATTRIBUTES_INSTRUCTOR on INSTRUCTOR_ATTRIBUTES USING btree (INSTRUCTOR_ID);
create index IDX_INSTRUCTOR_PREF_INSTRUCTOR on INSTRUCTOR_PREF USING btree (INSTRUCTOR_ID);
create index IDX_INSTRUCTOR_PREF_PREF_LEVEL on INSTRUCTOR_PREF USING btree (PREF_LEVEL_ID);
create index IDX_INSTRUCTOR_SURVEY_SESSION on INSTRUCTOR_SURVEY USING btree (SESSION_ID);
create index IDX_INSTR_CRSREQ_COURSE_OFFERING on INSTR_CRSREQ USING btree (COURSE_OFFERING_ID);
create index IDX_INSTR_CRSREQ_SURVEY on INSTR_CRSREQ USING btree (SURVEY_ID);
create index IDX_INSTR_CRSREQ_NOTE_TYPE on INSTR_CRSREQ_NOTE USING btree (TYPE_ID);
create index IDX_INSTR_OFFERING_CONFIG_DURATION_TYPE on INSTR_OFFERING_CONFIG USING btree (DURATION_TYPE_ID);
create index IDX_INSTR_OFFERING_CONFIG_INSTR_METHOD on INSTR_OFFERING_CONFIG USING btree (INSTR_METHOD_ID);
create index IDX_ITYPE_DESC_PARENT on ITYPE_DESC USING btree (PARENT);
create index IDX_LOCATION_PICTURE_LOCATION on LOCATION_PICTURE USING btree (LOCATION_ID);
create index IDX_LOCATION_PICTURE_TYPE on LOCATION_PICTURE USING btree (TYPE_ID);
create index IDX_LOCATION_SERVICE_PROVIDER_PROVIDER on LOCATION_SERVICE_PROVIDER USING btree (PROVIDER_ID);
create index IDX_MEETING_CONTACT_CONTACT on MEETING_CONTACT USING btree (CONTACT_ID);
create index IDX_NON_UNIVERSITY_LOCATION_ROOM_TYPE on NON_UNIVERSITY_LOCATION USING btree (ROOM_TYPE);
create index IDX_NON_UNIVERSITY_LOCATION_EVENT_DEPT on NON_UNIVERSITY_LOCATION USING btree (EVENT_DEPT_ID);
create index IDX_OFFERING_COORDINATOR_REQUEST on OFFERING_COORDINATOR USING btree (REQUEST_ID);
create index IDX_OFFERING_COORDINATOR_RESPONSIBILITY on OFFERING_COORDINATOR USING btree (RESPONSIBILITY_ID);
create index IDX_OFFERING_COORDINATOR_INSTRUCTOR on OFFERING_COORDINATOR USING btree (INSTRUCTOR_ID);
create index IDX_OFFERING_COORDINATOR_OFFERING on OFFERING_COORDINATOR USING btree (OFFERING_ID);
create index IDX_OFFR_GROUP_OFFERING_INSTR_OFFERING on OFFR_GROUP_OFFERING USING btree (INSTR_OFFERING_ID);
create index IDX_PIT_CLASS_FUNDING_DEPT on PIT_CLASS USING btree (FUNDING_DEPT_ID);
create index IDX_PIT_CLASS_CLASS on PIT_CLASS USING btree (CLASS_ID);
create index IDX_PIT_CLASS_MANAGING_DEPT on PIT_CLASS USING btree (MANAGING_DEPT);
create index IDX_PIT_CLASS_DATE_PATTERN on PIT_CLASS USING btree (DATE_PATTERN_ID);
create index IDX_PIT_CLASS_PIT_PARENT on PIT_CLASS USING btree (PIT_PARENT_ID);
create index IDX_PIT_CLASS_PIT_SUBPART on PIT_CLASS USING btree (PIT_SUBPART_ID);
create index IDX_PIT_CLASS_TIME_PATTERN on PIT_CLASS USING btree (TIME_PATTERN_ID);
create index IDX_PIT_CLASS_EVENT_PIT_CLASS on PIT_CLASS_EVENT USING btree (PIT_CLASS_ID);
create index IDX_PIT_CLASS_INSTRUCTOR_PIT_CLASS on PIT_CLASS_INSTRUCTOR USING btree (PIT_CLASS_ID);
create index IDX_PIT_CLASS_INSTRUCTOR_PIT_DEPT_INSTR on PIT_CLASS_INSTRUCTOR USING btree (PIT_DEPT_INSTR_ID);
create index IDX_PIT_CLASS_INSTRUCTOR_RESPONSIBILITY on PIT_CLASS_INSTRUCTOR USING btree (RESPONSIBILITY_ID);
create index IDX_PIT_CLASS_MEETING_PIT_CLASS_EVENT on PIT_CLASS_MEETING USING btree (PIT_CLASS_EVENT_ID);
create index IDX_PIT_CLASS_MTG_UTIL_PERIOD_PIT_CLASS_MEETING on PIT_CLASS_MTG_UTIL_PERIOD USING btree (PIT_CLASS_MEETING_ID);
create index IDX_PIT_COURSE_OFFERING_COURSE_OFFERING on PIT_COURSE_OFFERING USING btree (COURSE_OFFERING_ID);
create index IDX_PIT_COURSE_OFFERING_COURSE_TYPE on PIT_COURSE_OFFERING USING btree (COURSE_TYPE_ID);
create index IDX_PIT_COURSE_OFFERING_PIT_INSTR_OFFR on PIT_COURSE_OFFERING USING btree (PIT_INSTR_OFFR_ID);
create index IDX_PIT_COURSE_OFFERING_SUBJECT_AREA on PIT_COURSE_OFFERING USING btree (SUBJECT_AREA_ID);
create index IDX_PIT_DEPT_INSTRUCTOR_DEPARTMENT on PIT_DEPT_INSTRUCTOR USING btree (DEPARTMENT_ID);
create index IDX_PIT_DEPT_INSTRUCTOR_DEPT_INSTRUCTOR on PIT_DEPT_INSTRUCTOR USING btree (DEPT_INSTRUCTOR_ID);
create index IDX_PIT_DEPT_INSTRUCTOR_POINT_IN_TIME_DATA on PIT_DEPT_INSTRUCTOR USING btree (POINT_IN_TIME_DATA_ID);
create index IDX_PIT_DEPT_INSTRUCTOR_POS_CODE_TYPE on PIT_DEPT_INSTRUCTOR USING btree (POS_CODE_TYPE);
create index IDX_PIT_INSTR_OFFERING_INSTR_OFFERING on PIT_INSTR_OFFERING USING btree (INSTR_OFFERING_ID);
create index IDX_PIT_INSTR_OFFERING_POINT_IN_TIME_DATA on PIT_INSTR_OFFERING USING btree (POINT_IN_TIME_DATA_ID);
create index IDX_PIT_INSTR_OFFER_CONFIG_DURATION_TYPE on PIT_INSTR_OFFER_CONFIG USING btree (DURATION_TYPE_ID);
create index IDX_PIT_INSTR_OFFER_CONFIG_INSTR_METHOD on PIT_INSTR_OFFER_CONFIG USING btree (INSTR_METHOD_ID);
create index IDX_PIT_INSTR_OFFER_CONFIG_INSTR_OFFERING_CONFIG on PIT_INSTR_OFFER_CONFIG USING btree (INSTR_OFFERING_CONFIG_ID);
create index IDX_PIT_INSTR_OFFER_CONFIG_PIT_INSTR_OFFR on PIT_INSTR_OFFER_CONFIG USING btree (PIT_INSTR_OFFR_ID);
create index IDX_PIT_OFFERING_COORD_RESPONSIBILITY on PIT_OFFERING_COORD USING btree (RESPONSIBILITY_ID);
create index IDX_PIT_OFFERING_COORD_PIT_DEPT_INSTR on PIT_OFFERING_COORD USING btree (PIT_DEPT_INSTR_ID);
create index IDX_PIT_OFFERING_COORD_PIT_OFFERING on PIT_OFFERING_COORD USING btree (PIT_OFFERING_ID);
create index IDX_PIT_SCHED_SUBPART_ITYPE on PIT_SCHED_SUBPART USING btree (ITYPE);
create index IDX_PIT_SCHED_SUBPART_PIT_PARENT on PIT_SCHED_SUBPART USING btree (PIT_PARENT_ID);
create index IDX_PIT_SCHED_SUBPART_PIT_CONFIG on PIT_SCHED_SUBPART USING btree (PIT_CONFIG_ID);
create index IDX_PIT_SCHED_SUBPART_SCHEDULING_SUBPART on PIT_SCHED_SUBPART USING btree (SCHEDULING_SUBPART_ID);
create index IDX_PIT_STUDENT_POINT_IN_TIME_DATA on PIT_STUDENT USING btree (POINT_IN_TIME_DATA_ID);
create index IDX_PIT_STUDENT_STUDENT on PIT_STUDENT USING btree (STUDENT_ID);
create index IDX_PIT_STUDENT_CLASS_ENRL_PIT_CLASS on PIT_STUDENT_CLASS_ENRL USING btree (PIT_CLASS_ID);
create index IDX_PIT_STUDENT_CLASS_ENRL_PIT_COURSE_OFFERING on PIT_STUDENT_CLASS_ENRL USING btree (PIT_COURSE_OFFERING_ID);
create index IDX_PIT_STUDENT_CLASS_ENRL_PIT_STUDENT on PIT_STUDENT_CLASS_ENRL USING btree (PIT_STUDENT_ID);
create index IDX_PIT_STU_AA_MAJOR_CLASF_ACAD_AREA on PIT_STU_AA_MAJOR_CLASF USING btree (ACAD_AREA_ID);
create index IDX_PIT_STU_AA_MAJOR_CLASF_ACAD_CLASF on PIT_STU_AA_MAJOR_CLASF USING btree (ACAD_CLASF_ID);
create index IDX_PIT_STU_AA_MAJOR_CLASF_CONCENTRATION on PIT_STU_AA_MAJOR_CLASF USING btree (CONCENTRATION_ID);
create index IDX_PIT_STU_AA_MAJOR_CLASF_PIT_STUDENT on PIT_STU_AA_MAJOR_CLASF USING btree (PIT_STUDENT_ID);
create index IDX_PIT_STU_AA_MAJOR_CLASF_MAJOR on PIT_STU_AA_MAJOR_CLASF USING btree (MAJOR_ID);
create index IDX_PIT_STU_AA_MINOR_CLASF_ACAD_AREA on PIT_STU_AA_MINOR_CLASF USING btree (ACAD_AREA_ID);
create index IDX_PIT_STU_AA_MINOR_CLASF_ACAD_CLASF on PIT_STU_AA_MINOR_CLASF USING btree (ACAD_CLASF_ID);
create index IDX_PIT_STU_AA_MINOR_CLASF_PIT_STUDENT on PIT_STU_AA_MINOR_CLASF USING btree (PIT_STUDENT_ID);
create index IDX_PIT_STU_AA_MINOR_CLASF_MINOR on PIT_STU_AA_MINOR_CLASF USING btree (MINOR_ID);
create index IDX_POINT_IN_TIME_DATA_SESSION on POINT_IN_TIME_DATA USING btree (SESSION_ID);
create index IDX_POS_ACAD_AREA_MAJOR_MAJOR on POS_ACAD_AREA_MAJOR USING btree (MAJOR_ID);
create index IDX_POS_ACAD_AREA_MINOR_MINOR on POS_ACAD_AREA_MINOR USING btree (MINOR_ID);
create index IDX_POS_MAJOR_SESSION on POS_MAJOR USING btree (SESSION_ID);
create index IDX_POS_MAJOR_CONC_MAJOR on POS_MAJOR_CONC USING btree (MAJOR_ID);
create index IDX_POS_MINOR_SESSION on POS_MINOR USING btree (SESSION_ID);
create index IDX_RELATED_COURSE_INFO_COURSE on RELATED_COURSE_INFO USING btree (COURSE_ID);
create index IDX_RESERVATION_COURSE on RESERVATION USING btree (COURSE_ID);
create index IDX_RESERVATION_OFFERING on RESERVATION USING btree (OFFERING_ID);
create index IDX_RESERVATION_GROUP on RESERVATION USING btree (GROUP_ID);
create index IDX_RESERVATION_ACAD_AREA_AREA on RESERVATION_ACAD_AREA USING btree (AREA_ID);
create index IDX_RESERVATION_CLASF_ACAD_CLASF on RESERVATION_CLASF USING btree (ACAD_CLASF_ID);
create index IDX_RESERVATION_CLASS_CLASS on RESERVATION_CLASS USING btree (CLASS_ID);
create index IDX_RESERVATION_CONFIG_CONFIG on RESERVATION_CONFIG USING btree (CONFIG_ID);
create index IDX_RESERVATION_MAJOR_MAJOR on RESERVATION_MAJOR USING btree (MAJOR_ID);
create index IDX_RESERVATION_MAJOR_CONC_CONCENTRATION on RESERVATION_MAJOR_CONC USING btree (CONCENTRATION_ID);
create index IDX_RESERVATION_MINOR_MINOR on RESERVATION_MINOR USING btree (MINOR_ID);
create index IDX_RESERVATION_STUDENT_STUDENT on RESERVATION_STUDENT USING btree (STUDENT_ID);
create index IDX_ROOM_EVENT_DEPT on ROOM USING btree (EVENT_DEPT_ID);
create index IDX_ROOM_PARENT_ROOM on ROOM USING btree (PARENT_ROOM_ID);
create index IDX_ROOM_ROOM_TYPE on ROOM USING btree (ROOM_TYPE);
create index IDX_ROOM_EXAM_TYPE_EXAM_TYPE on ROOM_EXAM_TYPE USING btree (EXAM_TYPE_ID);
create index IDX_ROOM_FEATURE_FEATURE_TYPE on ROOM_FEATURE USING btree (FEATURE_TYPE_ID);
create index IDX_ROOM_FEATURE_SESSION on ROOM_FEATURE USING btree (SESSION_ID);
create index IDX_ROOM_JOIN_ROOM_FEATURE_FEATURE on ROOM_JOIN_ROOM_FEATURE USING btree (FEATURE_ID);
create index IDX_ROOM_PICTURE_LOCATION on ROOM_PICTURE USING btree (LOCATION_ID);
create index IDX_ROOM_PICTURE_TYPE on ROOM_PICTURE USING btree (TYPE_ID);
create index IDX_ROOM_SERVICE_PROVIDER_PROVIDER on ROOM_SERVICE_PROVIDER USING btree (PROVIDER_ID);
create index IDX_ROOM_TYPE_OPTION_DEPARTMENT on ROOM_TYPE_OPTION USING btree (DEPARTMENT_ID);
create index IDX_SCT_SOLUTION_LOG_OWNER on SCT_SOLUTION_LOG USING btree (OWNER_ID);
create index IDX_SCT_SOLUTION_LOG_SESSION on SCT_SOLUTION_LOG USING btree (SESSION_ID);
create index IDX_SECTIONING_COURSE_TYPES_COURSE_TYPE on SECTIONING_COURSE_TYPES USING btree (COURSE_TYPE_ID);
create index IDX_SECTIONING_INFO_CLASS on SECTIONING_INFO USING btree (CLASS_ID);
create index IDX_SECTIONING_LOG_SESSION on SECTIONING_LOG USING btree (SESSION_ID);
create index IDX_SECTIONING_STATUS_FALLBACK on SECTIONING_STATUS USING btree (FALLBACK_ID);
create index IDX_SECTIONING_STATUS_SESSION on SECTIONING_STATUS USING btree (SESSION_ID);
create index IDX_SERVICE_PROVIDER_DEPARTMENT on SERVICE_PROVIDER USING btree (DEPARTMENT_ID);
create index IDX_SERVICE_PROVIDER_SESSION on SERVICE_PROVIDER USING btree (SESSION_ID);
create index IDX_SESSIONS_DURATION_TYPE on SESSIONS USING btree (DURATION_TYPE_ID);
create index IDX_SESSIONS_INSTR_METHOD on SESSIONS USING btree (INSTR_METHOD_ID);
create index IDX_SESSIONS_SECT_STATUS on SESSIONS USING btree (SECT_STATUS);
create index IDX_SOLVER_GR_TO_TT_MGR_TIMETABLE_MGR on SOLVER_GR_TO_TT_MGR USING btree (TIMETABLE_MGR_ID);
create index IDX_SOLVER_INFO_SOLVER_INFO_DEF on SOLVER_INFO USING btree (SOLVER_INFO_DEF_ID);
create index IDX_STAFF_POS_TYPE on STAFF USING btree (POS_TYPE);
create index IDX_STANDARD_EVENT_NOTE_DEPARTMENT on STANDARD_EVENT_NOTE USING btree (DEPARTMENT_ID);
create index IDX_STANDARD_EVENT_NOTE_SESSION on STANDARD_EVENT_NOTE USING btree (SESSION_ID);
create index IDX_STUDENT_SECT_STATUS on STUDENT USING btree (SECT_STATUS);
create index IDX_STUDENT_ACAD_AREA_ACAD_AREA on STUDENT_ACAD_AREA USING btree (ACAD_AREA_ID);
create index IDX_STUDENT_ACAD_AREA_ACAD_CLASF on STUDENT_ACAD_AREA USING btree (ACAD_CLASF_ID);
create index IDX_STUDENT_ACCOMODATION_SESSION on STUDENT_ACCOMODATION USING btree (SESSION_ID);
create index IDX_STUDENT_ADVISOR_ADVISOR on STUDENT_ADVISOR USING btree (ADVISOR_ID);
create index IDX_STUDENT_AREA_CLASF_MAJOR_ACAD_AREA on STUDENT_AREA_CLASF_MAJOR USING btree (ACAD_AREA_ID);
create index IDX_STUDENT_AREA_CLASF_MAJOR_CAMPUS on STUDENT_AREA_CLASF_MAJOR USING btree (CAMPUS_ID);
create index IDX_STUDENT_AREA_CLASF_MAJOR_ACAD_CLASF on STUDENT_AREA_CLASF_MAJOR USING btree (ACAD_CLASF_ID);
create index IDX_STUDENT_AREA_CLASF_MAJOR_CONCENTRATION on STUDENT_AREA_CLASF_MAJOR USING btree (CONCENTRATION_ID);
create index IDX_STUDENT_AREA_CLASF_MAJOR_DEGREE on STUDENT_AREA_CLASF_MAJOR USING btree (DEGREE_ID);
create index IDX_STUDENT_AREA_CLASF_MAJOR_MAJOR on STUDENT_AREA_CLASF_MAJOR USING btree (MAJOR_ID);
create index IDX_STUDENT_AREA_CLASF_MAJOR_PROGRAM on STUDENT_AREA_CLASF_MAJOR USING btree (PROGRAM_ID);
create index IDX_STUDENT_AREA_CLASF_MINOR_ACAD_AREA on STUDENT_AREA_CLASF_MINOR USING btree (ACAD_AREA_ID);
create index IDX_STUDENT_AREA_CLASF_MINOR_ACAD_CLASF on STUDENT_AREA_CLASF_MINOR USING btree (ACAD_CLASF_ID);
create index IDX_STUDENT_AREA_CLASF_MINOR_MINOR on STUDENT_AREA_CLASF_MINOR USING btree (MINOR_ID);
create index IDX_STUDENT_GROUP_TYPE on STUDENT_GROUP USING btree (TYPE_ID);
create index IDX_STUDENT_MAJOR_MAJOR on STUDENT_MAJOR USING btree (MAJOR_ID);
create index IDX_STUDENT_MINOR_MINOR on STUDENT_MINOR USING btree (MINOR_ID);
create index IDX_STUDENT_TO_ACOMODATION_ACCOMODATION on STUDENT_TO_ACOMODATION USING btree (ACCOMODATION_ID);
create index IDX_STUDENT_TO_GROUP_GROUP on STUDENT_TO_GROUP USING btree (GROUP_ID);
create index IDX_SUBJECT_AREA_FUNDING_DEPT on SUBJECT_AREA USING btree (FUNDING_DEPT_ID);
create index IDX_TASK_OWNER on TASK USING btree (OWNER_ID);
create index IDX_TASK_SCRIPT on TASK USING btree (SCRIPT_ID);
create index IDX_TASK_SESSION on TASK USING btree (SESSION_ID);
create index IDX_TASK_EXECUTION_TASK on TASK_EXECUTION USING btree (TASK_ID);
create index IDX_TEACHING_REQUEST_OFFERING on TEACHING_REQUEST USING btree (OFFERING_ID);
create index IDX_TEACHING_REQUEST_RESPONSIBILITY on TEACHING_REQUEST USING btree (RESPONSIBILITY_ID);
create index IDX_TEACHING_REQUEST_SAME_COMMON_PREF on TEACHING_REQUEST USING btree (SAME_COMMON_PREF);
create index IDX_TEACHING_REQUEST_SAME_COURSE_PREF on TEACHING_REQUEST USING btree (SAME_COURSE_PREF);
create index IDX_TEACHREQ_CLASS_CLASS on TEACHREQ_CLASS USING btree (CLASS_ID);
create index IDX_TEACHREQ_CLASS_REQUEST on TEACHREQ_CLASS USING btree (REQUEST_ID);
create index IDX_TEACHREQ_INSTRUCTOR_INSTRUCTOR on TEACHREQ_INSTRUCTOR USING btree (INSTRUCTOR_ID);
create index IDX_TIME_PATTERN_DEPT_PATTERN on TIME_PATTERN_DEPT USING btree (PATTERN_ID);
create index IDX_TMTBL_MGR_TO_ROLES_ROLE on TMTBL_MGR_TO_ROLES USING btree (ROLE_ID);
create index IDX_TRAVEL_TIME_SESSION on TRAVEL_TIME USING btree (SESSION_ID);
create index IDX_XCONFLICT_INSTRUCTOR_INSTRUCTOR on XCONFLICT_INSTRUCTOR USING btree (INSTRUCTOR_ID);
create index IDX_XCONFLICT_STUDENT_STUDENT on XCONFLICT_STUDENT USING btree (STUDENT_ID);

/*
 * Update database version
 */
  
update application_config set value='270' where name='tmtbl.db.version';

commit;
